### ISSUE TITLE
Bildgalleri för olika modeller

### ISSUE THREAD

**Issue by jerkerjohansson** [synackdigital/jerkerinredning.se#17]

**Comment by frebro** [comment]
Kolla här @jerkerjohansson: [en förhandstitt på gallerifunktionen](http://cl.ly/duUA). Ska till pilar och lite sånt, men typ så här tänkte jag. Observera att det är dra-och-släpp som funkar fint på en platta/mobil.

**Comment by frebro** [comment]
Nu ligger gallerifunktionen uppe [på staging-servern](http://jerker.staging.wpengine.com/bokhyllor/) @jerkerjohansson -- ta en titt! Hoppas du gillar den. Säg till om du hittar buggar, för jag har inte hunnit testa ordentligt i olika läsare.

**Comment by jerkerjohansson** [comment]
Hej Fredrik,

Det ser bra ut! Kommer det fungera med lite mindre bilder. Justerar galleriet sig efter storleken på bilden? Blir bakgrunden något annat än grå. Det var väl det enda som såg lite tråkigt ut men jag vet ju om att det inte var färdigt än. Kanske kan vi använda en blurrad bild som bakgrund?


Med vänliga hälsningar,

Jerker Johansson

--

Jerker Inredning & Form

www.jerkerinredning.se
www.platsbyggdbokhylla.se
www.facebook.com/JerkerInredning

Norra Grängesbergsgatan 4
214 44 Malmö

0709 624 401

**Comment by frebro** [comment]
Äsch, jag tyckte den grå bakgrunden var lite snygg :)

Bilden tar så stor plats som den kan i skärmen. Om jag inte missat något så visas alltså hela bilden oavsett skärm och bildformat. 

Vill du kunna lägga till bildtexter? Känns inte som att det behövs tycker jag.

**Comment by frebro** [comment]
Blurrat bakgrundsfoto sparar jag som en bra idé. Absolut görbart, men lite pussligt.

**Comment by jerkerjohansson** [comment]
Kanske är överkurs med blurrat foto. Ta en ljusare grå/vit bara. Vore ju bra om bilderna hade taggar så att de är sökbara för google?
