### ISSUE TITLE
I bordkonfiguratorn. "annat" material ska inte ge ett pris

### ISSUE THREAD

**Issue by jerkerjohansson** [synackdigital/jerkerinredning.se#19]

**Comment by jerkerjohansson** [comment]
Såg snyggt ut med headern!

**Comment by jerkerjohansson** [comment]
Hur går det med denna? Kan du fixa snart? Pris för både Annat material och Annan ytbehandling ger priset 14.000kr

**Comment by frebro** [comment]
Det ska vara fixat @jerkerjohansson. Funkar fint för mig. Din cache kanske? Prova att ladda om sidan ett par gånger.
