### ISSUE TITLE
Byt typsnitt till Domine och Overpass/Roboto

### ISSUE THREAD

**Issue by frebro** [synackdigital/jerkerinredning.se#30]
Se samtidigt över alla typsnittsstorlekar. Ta bort underline i mellanrubrik.

**Comment by frebro** [comment]
Typsnitt bytta i ed766acd11ce5b9f990681c255f157628156d6fb

Eftersom både Domine och Roboto levereras gratis genom Google Webfontloader så använde jag dem. Vi kan lägga in Overpass senare om det verkar bättre. Eftersom de nya typsnitten skiljer sig rätt mycket från de gamla så gjorde jag om fontstorlekar överallt också. Ta en titt på http://jerker.staging.wpengine.com/ @jerkerjohansson

**Comment by jerkerjohansson** [comment]
Ser bra ut tycker jag. Vet ej om det är korrekt dock. Har svårt att jämföra :) Men du har koll på hur typsnitten ska se ut enligt manualen?


Med vänliga hälsningar,

Jerker Johansson

--

Jerker Inredning & Form

www.jerkerinredning.se
www.platsbyggdbokhylla.se
www.facebook.com/JerkerInredning

Norra Grängesbergsgatan 4
214 44 Malmö

0709 624 401

**Comment by frebro** [comment]
Ja, vi kollade ju på manualen sist och konstaterade att de typsnitten hon valt inte finns för webben. Vi valde ut ett par andra som är mycket lika (baserat på tips från https://www.typewolf.com/ som brukar har bra rekommendationer). Domine och Roboto är lika de typsnitt som du har i manualen, och de levereras i ett webbvänligt format via Google Fonts. Kolla gärna om hon som gjorde manualen har några synpunkter.
